version: '2.3'
services:
  ruby:
    build: ./docker/ruby/
    ports:
      - "3000:3000"
    volumes:
      - ./docker/ruby/srcs:/data
    environment:
      FT_TRANSCENDENCE_DATABASE_PASSWORD: password
      TZ: Europe/Paris
      42_OAUTH_CLIENT:
      42_OAUTH_SECRET:
      TOTP_KEY:
    tty: true
    stdin_open: true
    healthcheck:
      test: "curl -m 20 -f http://127.0.0.1:3000 || bash /data/ft_transcendence/kill.sh"
#      test: "ls"
      interval: 30s
      timeout: 30s
      retries: 2
      start_period: 60s
    restart: always
  postgresql:
    build: ./docker/postgresql
    environment:
      POSTGRES_PASSWORD: password
      TZ: Europe/Paris
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    volumes:
      - ./docker/redis/redis-data:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
